# Generated by Django 4.2.5 on 2023-10-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='call_id',
            new_name='call',
        ),
    ]
