---
- hosts: rails
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Add deploy user
      user:
        name: deploy
        shell: /bin/bash
    - name: Add SSH key to server for deploy user
      authorized_key:
        user: deploy
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJJgu0TT+E2+EIn9eTjRHBuZudklwF5rPj1d6qq3Lr9p7E94TzYLIqHdzIsNvwlRbpDNCt5PhEh3C24GFyhf/PJmVgPGTvNfUgrx7+v9sMsILtsvAbNVKGOvW1OAwLzaY8gDQNTt+T1F6e06e4c0fIsoTRxCWvBwDkBvHJQesNrPqM1rKQlFj6OdNO/GIVa3BMcnDfZ28pJRQAVonu/7VLFoYqYr+/hFpwuQ9yi34WKAuhKJP4jOmNBne44wSBGUIH2d20q+ZfonXf3zGMZYdZlrlmtjMwIN0IbBmV+0/7mLQKWUK+VLcZfRP0REWJIk1ZzeqDir8EzWrw8fGU+KOJO8l8L6LK9RL8y7pgRg48jxXFCMXjDxvV+lrITU72N8lrlZkxQFYuPmn9sQjnUzdzYPqeWEPyzth4Hj+qq7ARDnlSyiIBuE0ASSmreLwZu0jYDQzt0/GZAHs6ti6xHy9Wzck4W3PoHDzTtzp1UYSlSLZFGhFK5ZXm9y0VlKczl3GrduzYCLbZzgoC7yeOdGiDM5UbdruXDBcuVVLJSNCmucwf8f0IwCBLnL2nqHZGXev1inai5qS4XyKqxVUagNxkj6Q4dUBG+IJviRks+z97mI8579ouqxXamrZyGigZS1NbIvc67519eyGlvlYfm7XOeYfLNFX1qUV0sDzzKAbLpw== mykecameron@gmail.com"
    - name: Install Ruby dependencies
      apt:
        name:
          - autoconf
          - bison
          - build-essential
          - git-core
          - libcurl4-openssl-dev
          - libffi-dev
          - libgdbm-dev
          - libgdbm5
          - libncurses5-dev
          - libpq-dev
          - libreadline6-dev
          - libsqlite3-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
          - libyaml-dev
          - nodejs
          - postgresql-10
          - software-properties-common
          - sqlite3
          - yarn
          - zlib1g-dev
    - name: Clone rbenv
      git:
        repo: "https://github.com/rbenv/rbenv.git"
        dest: /home/deploy/.rbenv
    - name: Set correct owner and group for rbenv
      file: path=/home/deploy/.rbenv
        owner=deploy
        group=deploy
        recurse=yes
    - name: Install rbenv loader script
      copy: src=rbenv.sh
        dest=/etc/profile.d/rbenv.sh
    - name: Clone ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git
        dest=/home/deploy/.rbenv/plugins/ruby-build
        update=no
    - name: Set correct owner and group for ruby-build
      file: path=/home/deploy/.rbenv/plugins/ruby-build
        owner=deploy
        group=deploy
        recurse=yes
    - name: Install Ruby 2.7.1
      become_user: deploy
      command: "/home/deploy/.rbenv/bin/rbenv install 2.7.1"
      args:
        creates: /home/deploy/.rbenv/versions/2.7.1/bin/ruby
    - name: Install bundler
      become_user: deploy
      command: "rbenv shell 2.7.1 && gem install bundler"
      args:
        creates: /home/deploy/.rbenv/versions/2.7.1/bin/bundler
    - name: Install nginx
      apt:
        name: nginx
        state: latest
  roles:
  - role: zaiste.passenger
    nginx: extras
    passenger_app_vars:
    - name: RAILS_ENV
      value: production
